language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer update
    - touch coveralls-upload.json && chmod 777 coveralls-upload.json

script: php ./vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
